
GET http://localhost:1974/products/gap

###
GET https://restapi-722316705274.us-central1.run.app/products/gap


###
PATCH http://localhost:5000/products/uop
Content-Type: application/json

{
    "LKey":"jypIgyhvnxyL1HtVwmV4",
    "appCode":"456",
    "ClientName":"Umesh",
    "validUpto": "2023-01-30",
    "appName": "Expired"
}


###

### post http://localhost:5000/products/anp
POST  https://restapi-722316705274.us-central1.run.app/products/anp
Content-Type: application/json

{
    "appGroup": "2030",
    "appName": "Astro-Office - 2030",
    "validUpto": "04/30/2025"
    # "actCode": "",
    # "ClName": "",
    # "ClMobile": "",
    # "ClEmail": "",
    # "ClCity": "",
    # "dev1": "",
    # "dev2": "",
    # "dev3": "",
    # "dev4": "",
    # "consF": "",
    # "consU": "",
    # "intpro": "",
    # "actTS": "",
    # "lastCommTS": ""
    
}

###
delete http://localhost:5000/products/67809b1e340cb2c22549054a



###
POST http://localhost:5000/test
Content-Type: application/x-www-form-urlencoded

name=iMac&price=999


###
GET http://localhost:5000/client/anl
Content-Type: application/json

{
    "LKey": "phdp1YIShmZI01Pe85a7"
    
}

###
PATCH http://localhost:5000/client/anl
Content-Type: application/json

{
    "LKey": "phdp1YIShmZI01Pe85a7",
    "appGroup": "2030",
    "appName": "Astro-Office - 2030",
    "actCode": "1737022120590",
    "ClName": "Kamlesh",
    "ClMobile": "7666",
    "ClEmail": "kdp@gmail.com",
    "ClCity": "unr",
    "dev1": "1",
    "dev2": "2",
    "dev3": "3",
    "dev4": "4"
        
}

###
GET http://localhost:5000/client/gcd
Content-Type: application/json; charset=utf-8

{
    "LKey":"2wO7bY5rNYhsTw2JjDMu" 
}

###
PATCH http://localhost:5000/client/sudc
Content-Type: application/json

{
    "LKey":"2wO7bY5rNYhsTw2JjDMu",
    "ud4":"AA5EED10056FA1EBDE3CDF4D6CB35F626A30D4D2023518BC620B373AEA47C7651CA41E9B955901FC43F0503C4E144E851C3065E1EA1EDA882B14799AF9EB3083373C6E32"
}

###
PATCH http://localhost:1974/products/uofc
Content-Type: application/json

{
    "LKey":"lyAKCRdK1BYDlfTAIfmi" , 
    "consF":"262AAF29745304A399E8F3F6B1745BFC5B904BC1FAA2DD073701697221E8B63611CD3A1B3045570AA380EBD450BB27B4E392CD0B9C0E5619EEC32A3580DD2A34FCBE4F224F2851C1D9E0BDEA95DE1079C59E185B0EDC17BDEBC4BCDD07CE747987140DB6A95E135ED0D3DFDDDBEC"

}

###
POST http://pollution-monitor.com:8040/license/list
Content-Type: application/json

{
    "un":"admin" , 
    "pwd":"itsencryptedby" , 
    "sts":"01/01/2024" , 
    "ets":"01/25/2025"
}


### POST  https://restapi-722316705274.us-central1.run.app/products/anp
PATCH  http://localhost:1974/client/mkd
Content-Type: application/json

{
    "LKey":"xdeXHoSNdZrEFYlGWMrv",
    "appGroup":"2030",
    "appName":"Astro-Office - 2030",
    "validUpto":"04/30/2025"

}

###
# POST http://localhost:1974/client/gcd
POST https://restapi-722316705274.us-central1.run.app/client/gcd
# POST http://localhost:1974/client/gcd
Content-Type: application/json

{
    "LKey":"fMFJyHzKxkBw46IHWKC4"
}


###
# PATCH  https://restapi-722316705274.us-central1.run.app/admin/mkd
PATCH http://localhost:1974/products/mkd
Content-Type: application/json

{
    "LKey":"fMFJyHzKxkBw46IHWKC4",
    "appGroup":"2030",
    "appName":"Astro-Office - 2030",
    "validUpto":"04/30/2025"
    
}


###
# POST https://restapi-722316705274.us-central1.run.app/client/rofk
# "actCode":"175676664567",
POST http://localhost:1974/client/rofk
Content-Type: application/json

{
    "LKey":"fMFJyHzKxkBw46IHWKC4",
    "intpro": "192.168.0.103",
    "ClMobile":"k",
    "appName": "Astro-Office - 2030"
}

###
POST http://localhost:1974/client/vogk
Content-Type: application/json

{
    "otp":"6636FmC4"
}
### "LKey":"fMFJyHzKxkBw46IHWKC4",

###

POST http://pollution-monitor.com:8040/clientdetail
Content-Type: application/json

{
    "lk":"8F71CmQ3HZPJzurvn8ve"
}

###

POST http://pollution-monitor.com:8040/license/list
Content-Type: application/json

{   
    "un":"admin" , 
    "pwd":"itsencryptedby" , 
    "sts":"12/01/2024" , 
    "ets":"02/24/2025"
}

###

POST http://localhost:1974/client/gofvk
Content-Type: application/json

{
    "LKey":"fMFJyHzKxkBw46IHWKC4",
    "appGroup":"2030",
    "appName":"Astro-Office - 2030",
    "ClMobile": "k",
    "ac" : "1740309019937"
            
}
